version: '3.7'

services: 
  webapp1:
    image: nginx
    restart: always
    networks: 
      customer_3:
    container_name: webapp1 #Si defines el nombre a mano no fucniona el --scale 
    extra_hosts:
      - "pako:127.0.0.1"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.domain=juanito-remake.com"
      - "traefik.docker.network=customer_3"
      - "traefik.backend=webapp1"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:app1.juanito-remake.com"
      - "traefik.frontend.auth.basic.users=admin:$$apr1$$UiO3pJML$$rLv8Jl5740xq75HDmDw190"
  
  arsys-traefik-reverse-proxy:
    build:
      context: ./arsys-traefik
    image: localhost:8444/arsys/traefik-reverse-proxy:1.0.0
    command: 
      - "--api=true"
      - "--api.entrypoint=traefik"
      - "--api.dashboard=true"
      - "--ping"
      - "--docker"
      - "--docker.watch"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=juanito-remake.com"
      - "--logLevel=DEBUG"
    ports: 
      - "80:80"
    restart: always
    networks: 
      customer_1:
      customer_2:
      customer_3:
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.domain=juanito-remake.com"
      - "traefik.docker.network=customer_1"
      - "traefik.backend=arsys-traefik-reverse-proxy"
      - "traefik.backend.loadbalancer.stickiness=true"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.rule=Host:traefik.juanito-remake.com"
    depends_on:
      - webapp1
  wordpress_1:
      image: wordpress:5-php7.2
      restart: always
      #ports:
      #- "8080:80"
      environment:
        - "WORDPRESS_DB_HOST=mariadb_1"
        - "WORDPRESS_DB_USER=example"
        - "WORDPRESS_DB_PASSWORD=example"
        - "WORDPRESS_DB_NAME=example"
      networks: 
        customer_1:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.domain=juanito-remake.com"
        - "traefik.docker.network=customer_1"
        - "traefik.backend=wordpress_1"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.frontend.passHostHeader=true"
        - "traefik.frontend.rule=Host:wordpress.juanito-remake.com"
     
  wordpress_2:
    image: wordpress:5-php7.2
    restart: always
    #ports:
    #- "8080:80"
    environment:
      - "WORDPRESS_DB_HOST=mariadb_2"
      - "WORDPRESS_DB_USER=example"
      - "WORDPRESS_DB_PASSWORD=example"
      - "WORDPRESS_DB_NAME=example"
    networks: 
      customer_2:
    
  mariadb_1:
    image: mariadb:5.5.61
    restart: always
    environment: 
      - "MYSQL_DATABASE=example"
      - "MYSQL_USER=example"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=12345"
    networks: 
      customer_1:
   
  mariadb_2:
    image: mariadb:5.5.61
    restart: always
    environment: 
      - "MYSQL_DATABASE=example"
      - "MYSQL_USER=example"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=12345"
    networks: 
      customer_2:

networks:
  customer_1:
    name: customer_1
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 173.18.0.1/24

  customer_2:
    name: customer_2
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 173.19.0.1/24

  customer_3:
    name: customer_3
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 173.20.0.1/24